describe("Partial mpack extraction.", function()
    setup(function()
        require("smuggler").setup()
    end)
    it("Decodes numbers", function()
        local encoded = vim.mpack.encode(0)
        local success, result  = require("smuggler.partial_mpack").decode_one(encoded)
        assert.are.equals(success, true)
        assert.are.equals(result, 0)
    end)
    it("Decodes booleans", function()
        local encoded = vim.mpack.encode(false)
        local success, result = require("smuggler.partial_mpack").decode_one(encoded)
        assert.are.equals(success, true)
        assert.are.equals(result, false)
        encoded = vim.mpack.encode(true)
        success, result = require("smuggler.partial_mpack").decode_one(encoded)
        assert.are.equals(success, true)
        assert.are.equals(result, true)
    end)
    it("Decodes nil", function()
        local encoded = vim.mpack.encode(vim.NIL)
        local success, result = require("smuggler.partial_mpack").decode_one(encoded)
        assert.are.equals(success, true)
        assert.are.equals(result, vim.NIL)
    end)
    it("Decodes arrays", function()
        local encoded = vim.mpack.encode({1, 2, 3})
        local success, result = require("smuggler.partial_mpack").decode_one(encoded)
        assert.are.equals(success, true)
        assert.are.same(result, {1, 2, 3})
    end)
    it("Decodes strings", function()
        local encoded = vim.mpack.encode("test")
        local success, result = require("smuggler.partial_mpack").decode_one(encoded)
        assert.are.equals(success, true)
        assert.are.equals(result, "test")
    end)
    it("Decodes maps", function()
        local encoded = vim.mpack.encode({
            ["one"] = 1, 
            ["two"] = 2,
            ["three"] = 3
        })
        local success, result = require("smuggler.partial_mpack").decode_one(encoded)
        assert.are.equals(success, true)
        assert.are.same(result, {
            ["one"] = 1, 
            ["two"] = 2,
            ["three"] = 3
        })
    end)

end)
